language: cpp
dist: xenial

env:
  global:
    # Disable GCE boto plugin which is incompatible to Python 3, see
    # https://github.com/travis-ci/travis-ci/issues/5246
    - BOTO_CONFIG=/tmp/nowhere

matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc
      addons:
        apt:
          packages:
          - openssh-client
          - openssh-server
          - liblapack-pic
          - liblapack-dev
          - build-essential
          - make
          - libc6-dev
          - curl
          - git
          - texlive-base
          - texlive-latex-base
          - texlive-latex-extra
          - texlive-fonts-recommended
          - texlive-fonts-extra
          - texlive-pstricks
          - texlive-extra-utils
          - ghostscript

script:
  - make -C ${TRAVIS_BUILD_DIR}/doc VERBOSE=${VERBOSITY:-0}
